version: '3.9'

services:
  web:
    build: .
    container_name: django_news_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - web

networks:
  web:
    driver: bridge
