services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
    command:
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - /var/log:/var/log
    command:
      - "-config.file=/etc/promtail/promtail-config.yaml"
    depends_on:
      - loki

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
