# traefik/traefik.yml
entryPoints:
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      httpChallenge:
        entryPoint: websecure
      email: example@example.com
      storage: acme.json

providers:
  file:
    filename: /etc/traefik/traefik_dynamic.yaml